{{- if .Values.serviceMonitor.enabled }}
# nginx-prometheus-exporter sidecar 없이 stub_status 직접 스크래핑
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: plask-frontend
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    app: plask-frontend
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - plask
  selector:
    matchLabels:
      app: plask-frontend
  endpoints:
    - port: http
      path: /stub_status
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
